services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: exsi
      POSTGRES_PASSWORD: testhome
      POSTGRES_DB: ntDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_pg_hba.sh:/docker-entrypoint-initdb.d/init_pg_hba.sh

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://exsi:testhome@postgres:5432/ntDB?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  influxdb:
    image: influxdb:1.11
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./init_influx.sh:/docker-entrypoint-initdb.d/init_influx.sh

  grafana:
    image: grafana/grafana:10.1.4-ubuntu
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=testhome
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning #Провиженинг
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  prometheus:
    image: prom/prometheus:v2.47.1
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/configuration/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      
  node_exporter:
    image: prom/node-exporter:v1.3.1
    restart: always
    ports:
      - "9100:9100"
    
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "K9HVUQVlQRe0k9CoR7sgKg"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_LISTENERS: "INTERNAL://:9091,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9091,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9091"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
  prometheus_data:
  kafka_data:

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
