apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.3.2:9090
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://192.168.3.2:8086
    database: nt_test_db
    jsonData:
      httpMode: GET
